export const SELECT_NODE = 'SELECT_NODE';
export const SELECT_NODES = 'SELECT_NODES';
export const HIGHLIGHT_NODES = 'HIGHLIGHT_NODES';
export const DELETE_NODES = 'DELETE_NODES';
export const CLEAR_SELECTION = 'CLEAR_SELECTION';