export const AUTH_CONNECTED = 'AUTH_CONNECTED';
export const CANCEL_REQUEST = 'CANCEL_REQUEST';
export const REQUEST_COMPLETED = 'REQUEST_COMPLETED';
export const WEB_SOCKET_CONNECT = 'WEB_SOCKET_CONNECT';
export const WEB_SOCKET_SEND = 'WEB_SOCKET_SEND';
export const ERROR = 'ERROR';