export const DATASOURCE_ACTIVATED = 'DATASOURCE_ACTIVATED';
export const DATASOURCE_DEACTIVATED = 'DATASOURCE_DEACTIVATED';
export const INITIAL_STATE_RECEIVE = "INITIAL_STATE_RECEIVE";
export const UPDATE_DATASOURCE = 'UPDATE_DATASOURCE';