export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_RECEIVE = 'SEARCH_RECEIVE';
export const SEARCH_DELETE = 'SEARCH_DELETE';
export const SEARCH_EDIT = 'SEARCH_EDIT';
export const FILTER_SEARCH_RESULTS = 'FILTER_SEARCH_RESULTS';